<a href="https://colab.research.google.com/github/maggiecrowner/DS5001-Final-Project/blob/main/LDA_THETA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LDA

In [1]:
! git clone https://github.com/maggiecrowner/DS5001-Final-Project.git

Cloning into 'DS5001-Final-Project'...
remote: Enumerating objects: 287, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 287 (delta 64), reused 4 (delta 4), pack-reused 175 (from 1)
Receiving objects: 100% (287/287), 15.07 MiB | 8.12 MiB/s, done.
Resolving deltas: 100% (115/115), done.

In [2]:
!wget -O CORPUS.csv "https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv"
!wget -O LIB.csv "https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv"

--2026-04-21 02:37:38--  https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-21 02:37:39--  https://virginia.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-21 02:37:39--  https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!_PC7kfmRDt1IYQ_-ZLkoSH3Snwkp2y4cvvN-EJQm41EwBjBuDp_CJl2bBQ2sjIIAe8qHn44MkpcZ5YyuHhgBwmbwd77lDfRYVWgBOJ6uSssyMFrf3GlxRbmFnmkpPNbigNpJGSPKoqNa0lr4zFyOxB6CtkXmoGteOZjgZCIeBbAhj8vIlWSmX2pudvY0us02ket5Z2Z4qCcg1L2gJGPzOujiJPDhFKtml0tU8Y7WYuUxjJisgfJplBJPh-1pELd0RgSr2H5uiZhaYmuT3NHLI-hj9NWKkaRnbcDHguT0u00e2Dswsc9cBE7CJCHszJcOmZGj3VNlRHuGGsDGFjjAPS2M5H74nnwLJ1Dajkm25yFnqKnxXLvDDmm3nyexFr05tG4EwHKqjGuBgQyollN6lzEYRSySQcqtJQRqfvz27UAMVFtBU6XJi--Q9Cg4S9m_A2lAN4jj_WMh37-e7nKyd5HPlMEChW1-o0A1z2JR6TBQnLMDjMcNpIYjNo0lh9dVxlBj79CrcIIXaWCcRc6-wHBXE5jzQqdR55fM5cPC3t29TjbJ7C576AhkpKti5QBdW1b9a3sNR90OZgZB8ymghC5N6LiqRord-riaaWSxQFZInz4rnKRkzLcMLjH6bpkYP9P3xJuFgFpDKsdu1tHgD0EcWvKpe9nw1PGsD1NyL83DNGeyGw2LN43Zz3kMHR3TYOvW5QYFeg1al12VGguiXRKBO7NW1nZUEabQzFs3ClQxMKuTU4HS667tAAtoDu3Ka729LwcFetClSvE7SsBihrkvJCb5OCvumpVdhKfgRqYLf1oEBbIUo84UzCY1G3hzzv9tWXe5uim2yX_SN3wEWtiQsPSwhfEGS2tRAg7HGVq-7C0Y5KbfTHNxYNwV44ZBZJX63fB1KaCVGWBAeujGsSiblkET-aeHRq0uxINjSWTkF9PcTEzKTFSSamrIXtVcN91M1-yIzQUcGhla4UBmZ14DhwjL8zekaOkeTtfDoumvGfAwq5x0u1fYuw4wi9ha2Yol--dP7HdPvDS1oTvXVPbyPhFF6X3KWe273vtKGwK5otdY1sJwLnk369VO9CanytgadQVLTXl0NQORZV76MwxDd6magXBniQF9My_4AlQclVUAxdWeGOaw3-0aomB1K-GKs5rh5kbkaeH6nTX_jyVQM912Y5RvmdMEsJdqfShQDVY95miiuRS7osVCtjzGyeM6tg8nHnoDKWWFJuHu5tmrCcftTdTOS1_CIfsdz3OwpisvBkcQvZpRrWc0mYzDvBDjAEmI-uLPXJhkvurjI4v4i_iyxif-Otpm3xF2PsyR-xANdZR3tlXmBoojhqBtIA0PQ4JjkMnqO-6hxK2SapzRIqv5TpOUZtUfT053T_oRfEUED1mx-D0krwrLXpdiD7FwoVHsfKsyIfFYaXI1vw73wW2CNW_aQB670cHn5kqyrBLwbN0wirDrOGWdPchQsVFMVo2ckJhW9EFKgEJrLvg9j1ef9w../download [following]
--2026-04-21 02:37:40--  https://public.boxcloud.com/d/1/b1!_PC7kfmRDt1IYQ_-ZLkoSH3Snwkp2y4cvvN-EJQm41EwBjBuDp_CJl2bBQ2sjIIAe8qHn44MkpcZ5YyuHhgBwmbwd77lDfRYVWgBOJ6uSssyMFrf3GlxRbmFnmkpPNbigNpJGSPKoqNa0lr4zFyOxB6CtkXmoGteOZjgZCIeBbAhj8vIlWSmX2pudvY0us02ket5Z2Z4qCcg1L2gJGPzOujiJPDhFKtml0tU8Y7WYuUxjJisgfJplBJPh-1pELd0RgSr2H5uiZhaYmuT3NHLI-hj9NWKkaRnbcDHguT0u00e2Dswsc9cBE7CJCHszJcOmZGj3VNlRHuGGsDGFjjAPS2M5H74nnwLJ1Dajkm25yFnqKnxXLvDDmm3nyexFr05tG4EwHKqjGuBgQyollN6lzEYRSySQcqtJQRqfvz27UAMVFtBU6XJi--Q9Cg4S9m_A2lAN4jj_WMh37-e7nKyd5HPlMEChW1-o0A1z2JR6TBQnLMDjMcNpIYjNo0lh9dVxlBj79CrcIIXaWCcRc6-wHBXE5jzQqdR55fM5cPC3t29TjbJ7C576AhkpKti5QBdW1b9a3sNR90OZgZB8ymghC5N6LiqRord-riaaWSxQFZInz4rnKRkzLcMLjH6bpkYP9P3xJuFgFpDKsdu1tHgD0EcWvKpe9nw1PGsD1NyL83DNGeyGw2LN43Zz3kMHR3TYOvW5QYFeg1al12VGguiXRKBO7NW1nZUEabQzFs3ClQxMKuTU4HS667tAAtoDu3Ka729LwcFetClSvE7SsBihrkvJCb5OCvumpVdhKfgRqYLf1oEBbIUo84UzCY1G3hzzv9tWXe5uim2yX_SN3wEWtiQsPSwhfEGS2tRAg7HGVq-7C0Y5KbfTHNxYNwV44ZBZJX63fB1KaCVGWBAeujGsSiblkET-aeHRq0uxINjSWTkF9PcTEzKTFSSamrIXtVcN91M1-yIzQUcGhla4UBmZ14DhwjL8zekaOkeTtfDoumvGfAwq5x0u1fYuw4wi9ha2Yol--dP7HdPvDS1oTvXVPbyPhFF6X3KWe273vtKGwK5otdY1sJwLnk369VO9CanytgadQVLTXl0NQORZV76MwxDd6magXBniQF9My_4AlQclVUAxdWeGOaw3-0aomB1K-GKs5rh5kbkaeH6nTX_jyVQM912Y5RvmdMEsJdqfShQDVY95miiuRS7osVCtjzGyeM6tg8nHnoDKWWFJuHu5tmrCcftTdTOS1_CIfsdz3OwpisvBkcQvZpRrWc0mYzDvBDjAEmI-uLPXJhkvurjI4v4i_iyxif-Otpm3xF2PsyR-xANdZR3tlXmBoojhqBtIA0PQ4JjkMnqO-6hxK2SapzRIqv5TpOUZtUfT053T_oRfEUED1mx-D0krwrLXpdiD7FwoVHsfKsyIfFYaXI1vw73wW2CNW_aQB670cHn5kqyrBLwbN0wirDrOGWdPchQsVFMVo2ckJhW9EFKgEJrLvg9j1ef9w../download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.164, 2620:117:bff0:e2::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 69963573 (67M) [text/csv]
Saving to: ‘CORPUS.csv’

CORPUS.csv          100%[===================>]  66.72M  46.7MB/s    in 1.4s

2026-04-21 02:37:41 (46.7 MB/s) - ‘CORPUS.csv’ saved [69963573/69963573]

--2026-04-21 02:37:42--  https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-21 02:37:42--  https://virginia.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-21 02:37:42--  https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!CejoJHuKfh6lgALpqGY2apNY0OxZBRXfhNp9TXqrSh3fDZDcgi_An35frRez0AgOPcDOwet4khu1A5BXqHmCmjnuZxv5qIc5S5mz_Z-yLsNRhqNWfMMInVZLH3oJDqSz0_lA__tNbAj9K-tPgrGaw1aE9QRga295dNI7WDPv6gB92jYbESKneHN3J11y7vEBGLgZuNIgpuHMgFNGK9rQ1k6cMhGIMZk5IdzANF69lkCwMc29_pGbEUN7nyZy2MHU1wo1sahvUm7hGQ5psaGs3vQ7x-glIKtGxyz4YRRSz6b8geShcbWRfed1QCtrWInfVrmsK0Ro_oggZ7Ww972j3zagLZAFXvt3qvi6AA18jSlLaVFU4NDQtUyCpc83Ku_zH2tjnqZOPcRiYjeGNqrWnuSzjEhxzbw-Vj-EDjLPrHcvcrLhsHW6GAhyhDoX8CF3nV7tNU-56e-5IFggHLHDYGA9mfiYDNx-ZlKw5Hi9VflAHSWJ-ktVHzAPH_opOWzrKKm_wok2D2do8C4hW3UNqdljfoMznPjj1IP9lm0E44JKwrJ_JECbxsiBanXES-zG64MktJf3uwMQ_1tT1-e3kAmCgep6vSYcUkCb6DXA5epbu6BQSojitLML4siK9sy-mN7VzTMFHfe0waz_-lPhCAir42P0_Mids4TjMJ0O8B5dfIRfVZ1GXD4ZszDHJHBxx0LjMGv4AZmvQEMygATyYwAoysm2YO8CFaWLTEVN1YaKYxrcNCNbrC2sQnIakMzabO1znORq3ZN40C1gPjLNXPAnNucUeZvkDXy3a13RMbtqS948TqawZ8TbnlEOcWaZuCwXBKi5mZv8l58UyFRHrTAEaRexh0EJ5jotXlFdzOnkzpPeKP3qgTb4Svx5K_OYWNCNZUkCvGQcKipdcM0P7fNGTBd8av919jN2tsv_cqGaVNM_oniqH9KSFT-Rqn3ebbvUCXg7SpDzEa-41ejVtUn-nN-fd45vqkxfJQpokVnqowkr6E6VyAI612PyVg7YLyKHWsfVX0wp1LJMhZvLBjuZT0zVn_fKJFPV1I4H3VpV07PpbAuTRtJ6ax8LF-_uSYvI1pEGnztDZcrctaYP1IP7BoySLpU7OJzfKWQJFK4UXhKmfpFPlPPQygD3IVp1nm4RA67x2EsTYtLTNltyfxcnueUA9yHncMbJHvFk-jZc4lY8tSiHmVrDHJdqmXjdoMM9UmMg7B3JXAxuiPRv3zO3df2jgqixL5aDLCQXdPAgR-FWtN_tpTrnwgau2nm4-uR6yg7MLKvwHm5W3WrIBytBn-_uwMgBsnUn3Y5VLPKx4J6FGEL_tuyMBa8kEoxfynfi5oO1Osl4y58RX0cqQ_xxBh_COo3stLjQgc5SvKZRyDQZ1y4j4il9DdFsm1OYQO_mDjelXP3ab3kbYIF1lG4eoHr4d-e2XbizfAYkQ44DL2TefQ7HdBZ03XCZrsAi2RuNweOyMDrOBByoEott6HQ./download [following]
--2026-04-21 02:37:42--  https://public.boxcloud.com/d/1/b1!CejoJHuKfh6lgALpqGY2apNY0OxZBRXfhNp9TXqrSh3fDZDcgi_An35frRez0AgOPcDOwet4khu1A5BXqHmCmjnuZxv5qIc5S5mz_Z-yLsNRhqNWfMMInVZLH3oJDqSz0_lA__tNbAj9K-tPgrGaw1aE9QRga295dNI7WDPv6gB92jYbESKneHN3J11y7vEBGLgZuNIgpuHMgFNGK9rQ1k6cMhGIMZk5IdzANF69lkCwMc29_pGbEUN7nyZy2MHU1wo1sahvUm7hGQ5psaGs3vQ7x-glIKtGxyz4YRRSz6b8geShcbWRfed1QCtrWInfVrmsK0Ro_oggZ7Ww972j3zagLZAFXvt3qvi6AA18jSlLaVFU4NDQtUyCpc83Ku_zH2tjnqZOPcRiYjeGNqrWnuSzjEhxzbw-Vj-EDjLPrHcvcrLhsHW6GAhyhDoX8CF3nV7tNU-56e-5IFggHLHDYGA9mfiYDNx-ZlKw5Hi9VflAHSWJ-ktVHzAPH_opOWzrKKm_wok2D2do8C4hW3UNqdljfoMznPjj1IP9lm0E44JKwrJ_JECbxsiBanXES-zG64MktJf3uwMQ_1tT1-e3kAmCgep6vSYcUkCb6DXA5epbu6BQSojitLML4siK9sy-mN7VzTMFHfe0waz_-lPhCAir42P0_Mids4TjMJ0O8B5dfIRfVZ1GXD4ZszDHJHBxx0LjMGv4AZmvQEMygATyYwAoysm2YO8CFaWLTEVN1YaKYxrcNCNbrC2sQnIakMzabO1znORq3ZN40C1gPjLNXPAnNucUeZvkDXy3a13RMbtqS948TqawZ8TbnlEOcWaZuCwXBKi5mZv8l58UyFRHrTAEaRexh0EJ5jotXlFdzOnkzpPeKP3qgTb4Svx5K_OYWNCNZUkCvGQcKipdcM0P7fNGTBd8av919jN2tsv_cqGaVNM_oniqH9KSFT-Rqn3ebbvUCXg7SpDzEa-41ejVtUn-nN-fd45vqkxfJQpokVnqowkr6E6VyAI612PyVg7YLyKHWsfVX0wp1LJMhZvLBjuZT0zVn_fKJFPV1I4H3VpV07PpbAuTRtJ6ax8LF-_uSYvI1pEGnztDZcrctaYP1IP7BoySLpU7OJzfKWQJFK4UXhKmfpFPlPPQygD3IVp1nm4RA67x2EsTYtLTNltyfxcnueUA9yHncMbJHvFk-jZc4lY8tSiHmVrDHJdqmXjdoMM9UmMg7B3JXAxuiPRv3zO3df2jgqixL5aDLCQXdPAgR-FWtN_tpTrnwgau2nm4-uR6yg7MLKvwHm5W3WrIBytBn-_uwMgBsnUn3Y5VLPKx4J6FGEL_tuyMBa8kEoxfynfi5oO1Osl4y58RX0cqQ_xxBh_COo3stLjQgc5SvKZRyDQZ1y4j4il9DdFsm1OYQO_mDjelXP3ab3kbYIF1lG4eoHr4d-e2XbizfAYkQ44DL2TefQ7HdBZ03XCZrsAi2RuNweOyMDrOBByoEott6HQ./download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.164, 2620:117:bff0:e2::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 324648 (317K) [text/csv]
Saving to: ‘LIB.csv’

LIB.csv             100%[===================>] 317.04K  --.-KB/s    in 0.06s

2026-04-21 02:37:43 (5.13 MB/s) - ‘LIB.csv’ saved [324648/324648]

In [3]:
import pandas as pd
CORPUS = pd.read_csv('CORPUS.csv', delimiter='|', index_col=[0,1,2,3])
LIB = pd.read_csv('LIB.csv', delimiter='|', index_col=0)

In [4]:
DOCS = CORPUS[CORPUS.pos.str.match(r'^NNS?$')]\
    .groupby(['Artist', 'Album', 'Title']).term_str\
    .apply(lambda x: ' '.join(map(str,x)))\
    .to_frame()\
    .rename(columns={'term_str':'doc_str'})

In [5]:
from sklearn.feature_extraction import text
my_stop_words = list(text.ENGLISH_STOP_WORDS)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
count_engine = CountVectorizer(max_df=.9, min_df=10, stop_words=my_stop_words)
count_model = count_engine.fit_transform(DOCS.doc_str)
TERMS = count_engine.get_feature_names_out()
VOCAB = pd.DataFrame(index=TERMS)
VOCAB.index.name = 'term_str'
COUNTS = pd.DataFrame(count_model.toarray(), index=DOCS.index, columns=TERMS)
COUNTS

                                                                               act  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                0
              Ariana Grande                         Ariana Grande Tour Guide     0
                                                    I’m Every Woman/Vogue        0
                                                    Leave Me Lonely (Reprise)    0
                                                    Love Me Harder/breathin      0
...                                                                            ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                    0
                                                    My Turn To Be Me             0
                                                    Never Fade                   0
                                                    Point of View                0
                                                    Smokey Black Nights          0

                                                                               adam  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 0
              Ariana Grande                         Ariana Grande Tour Guide      0
                                                    I’m Every Woman/Vogue         0
                                                    Leave Me Lonely (Reprise)     0
                                                    Love Me Harder/breathin       0
...                                                                             ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                     0
                                                    My Turn To Be Me              0
                                                    Never Fade                    0
                                                    Point of View                 0
                                                    Smokey Black Nights           0

                                                                               advice  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                   0
              Ariana Grande                         Ariana Grande Tour Guide        0
                                                    I’m Every Woman/Vogue           0
                                                    Leave Me Lonely (Reprise)       0
                                                    Love Me Harder/breathin         0
...                                                                               ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                       0
                                                    My Turn To Be Me                0
                                                    Never Fade                      0
                                                    Point of View                   0
                                                    Smokey Black Nights             0

                                                                               affection  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                      0
              Ariana Grande                         Ariana Grande Tour Guide           0
                                                    I’m Every Woman/Vogue              0
                                                    Leave Me Lonely (Reprise)          0
                                                    Love Me Harder/breathin            0
...                                                                                  ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                          0
                                                    My Turn To Be Me                   0
                                                    Never Fade                         0
                                                    Point of View                      0
                                                    Smokey Black Nights                0

                                                                               afraid  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                   0
              Ariana Grande                         Ariana Grande Tour Guide        0
                                                    I’m Every Woman/Vogue           0
                                                    Leave Me Lonely (Reprise)       0
                                                    Love Me Harder/breathin         0
...                                                                               ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                       0
                                                    My Turn To Be Me                0
                                                    Never Fade                      0
                                                    Point of View                   0
                                                    Smokey Black Nights             0

                                                                               afternoon  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                      0
              Ariana Grande                         Ariana Grande Tour Guide           0
                                                    I’m Every Woman/Vogue              0
                                                    Leave Me Lonely (Reprise)          0
                                                    Love Me Harder/breathin            0
...                                                                                  ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                          0
                                                    My Turn To Be Me                   0
                                                    Never Fade                         0
                                                    Point of View                      0
                                                    Smokey Black Nights                0

                                                                               age  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                0
              Ariana Grande                         Ariana Grande Tour Guide     0
                                                    I’m Every Woman/Vogue        0
                                                    Leave Me Lonely (Reprise)    0
                                                    Love Me Harder/breathin      0
...                                                                            ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                    0
                                                    My Turn To Be Me             0
                                                    Never Fade                   0
                                                    Point of View                0
                                                    Smokey Black Nights          0

                                                                               ah  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You               0
              Ariana Grande                         Ariana Grande Tour Guide    0
                                                    I’m Every Woman/Vogue       0
                                                    Leave Me Lonely (Reprise)   0
                                                    Love Me Harder/breathin     0
...                                                                            ..
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                   0
                                                    My Turn To Be Me            0
                                                    Never Fade                  0
                                                    Point of View               0
                                                    Smokey Black Nights         0

                                                                               ahah  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 0
              Ariana Grande                         Ariana Grande Tour Guide      0
                                                    I’m Every Woman/Vogue         0
                                                    Leave Me Lonely (Reprise)     0
                                                    Love Me Harder/breathin       0
...                                                                             ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                     0
                                                    My Turn To Be Me              0
                                                    Never Fade                    0
                                                    Point of View                 0
                                                    Smokey Black Nights           0

                                                                               ahh  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                0
              Ariana Grande                         Ariana Grande Tour Guide     0
                                                    I’m Every Woman/Vogue        0
                                                    Leave Me Lonely (Reprise)    0
                                                    Love Me Harder/breathin      0
...                                                                            ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                    0
                                                    My Turn To Be Me             0
                                                    Never Fade                   0
                                                    Point of View                0
                                                    Smokey Black Nights          0

                                                                               ...  \
Artist        Album                                 Title                      ...
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              ...
              Ariana Grande                         Ariana Grande Tour Guide   ...
                                                    I’m Every Woman/Vogue      ...
                                                    Leave Me Lonely (Reprise)  ...
                                                    Love Me Harder/breathin    ...
...                                                                            ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                  ...
                                                    My Turn To Be Me           ...
                                                    Never Fade                 ...
                                                    Point of View              ...
                                                    Smokey Black Nights        ...

                                                                               yesterday  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                      0
              Ariana Grande                         Ariana Grande Tour Guide           0
                                                    I’m Every Woman/Vogue              0
                                                    Leave Me Lonely (Reprise)          0
                                                    Love Me Harder/breathin            0
...                                                                                  ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                          0
                                                    My Turn To Be Me                   0
                                                    Never Fade                         0
                                                    Point of View                      0
                                                    Smokey Black Nights                0

                                                                               yo  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You               0
              Ariana Grande                         Ariana Grande Tour Guide    0
                                                    I’m Every Woman/Vogue       0
                                                    Leave Me Lonely (Reprise)   0
                                                    Love Me Harder/breathin     0
...                                                                            ..
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                   0
                                                    My Turn To Be Me            0
                                                    Never Fade                  0
                                                    Point of View               0
                                                    Smokey Black Nights         0

                                                                               york  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 0
              Ariana Grande                         Ariana Grande Tour Guide      0
                                                    I’m Every Woman/Vogue         0
                                                    Leave Me Lonely (Reprise)     0
                                                    Love Me Harder/breathin       0
...                                                                             ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                     0
                                                    My Turn To Be Me              0
                                                    Never Fade                    0
                                                    Point of View                 0
                                                    Smokey Black Nights           0

                                                                               youd  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 0
              Ariana Grande                         Ariana Grande Tour Guide      0
                                                    I’m Every Woman/Vogue         0
                                                    Leave Me Lonely (Reprise)     0
                                                    Love Me Harder/breathin       0
...                                                                             ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                     0
                                                    My Turn To Be Me              0
                                                    Never Fade                    0
                                                    Point of View                 0
                                                    Smokey Black Nights           0

                                                                               youll  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0
              Ariana Grande                         Ariana Grande Tour Guide       0
                                                    I’m Every Woman/Vogue          0
                                                    Leave Me Lonely (Reprise)      0
                                                    Love Me Harder/breathin        0
...                                                                              ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                      0
                                                    My Turn To Be Me               0
                                                    Never Fade                     0
                                                    Point of View                  0
                                                    Smokey Black Nights            0

                                                                               youre  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0
              Ariana Grande                         Ariana Grande Tour Guide       0
                                                    I’m Every Woman/Vogue          0
                                                    Leave Me Lonely (Reprise)      0
                                                    Love Me Harder/breathin        0
...                                                                              ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                      0
                                                    My Turn To Be Me               0
                                                    Never Fade                     2
                                                    Point of View                  0
                                                    Smokey Black Nights            0

                                                                               youth  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0
              Ariana Grande                         Ariana Grande Tour Guide       0
                                                    I’m Every Woman/Vogue          0
                                                    Leave Me Lonely (Reprise)      0
                                                    Love Me Harder/breathin        0
...                                                                              ...
Taylor Swift  “Taylor’s Songs” 2003 Demo            Lucky You                      0
                                                    My Turn To Be Me               0
                                                    Never Fade                     0
                                                    Point of View                  0
                                                    Smokey Black Nights            0

                                                                               youve  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0
              Ariana Grande                         Ariana Grande Tour Guide       0
                                                    I’m Every Woman/Vogue          0
                                                    Leave Me Lonely (Reprise)      0

In [7]:
COUNTS.to_csv("/content/DS5001-Final-Project/COUNTS.csv", sep="|", index=True)

In [8]:
import numpy as np
from sklearn.decomposition import LatentDirichletAllocation as LDA

n_topics = 20
max_iter = 100
n_top_terms = 9
TNAMES = [f"T{str(x).zfill(len(str(n_topics)))}" for x in range(n_topics)]
topic_engine = LDA(n_components=20, random_state=42)
topic_model = topic_engine.fit_transform(count_model)

## THETA

In [9]:
THETA = pd.DataFrame(topic_model, index=DOCS.index, columns=TNAMES)
THETA.columns.name = 'topic_id'
THETA.head()

topic_id                                                                            T00  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.038265
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T01  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.037843
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T02  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.224402
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T03  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.238869
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T04  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.128415
                                                    Leave Me Lonely (Reprise)  0.207473
                                                    Love Me Harder/breathin    0.022615

topic_id                                                                            T05  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T06  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.822580

topic_id                                                                            T07  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T08  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.461324
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T09  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.121533
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T10  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T11  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T12  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.726590
              Ariana Grande                         Ariana Grande Tour Guide   0.382230
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T13  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.116237
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T14  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.107638
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.041775

topic_id                                                                            T15  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.454311
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T16  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T17  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.001250
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T18  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.152320
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.318282
                                                    Leave Me Lonely (Reprise)  0.002500
                                                    Love Me Harder/breathin    0.000685

topic_id                                                                            T19
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.099840
              Ariana Grande                         Ariana Grande Tour Guide   0.002778
                                                    I’m Every Woman/Vogue      0.000704
                                                    Leave Me Lonely (Reprise)  0.066801
                                                    Love Me Harder/breathin    0.102071

In [10]:
THETA.to_csv("/content/DS5001-Final-Project/THETA.csv", sep="|", index=True)