<a href="https://colab.research.google.com/github/maggiecrowner/DS5001-Final-Project/blob/main/Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Models

In [2]:
! git clone https://github.com/maggiecrowner/DS5001-Final-Project.git

fatal: destination path 'DS5001-Final-Project' already exists and is not an empty directory.

In [3]:
!wget -O TFIDF_L2.csv "https://virginia.box.com/shared/static/959w70gbj2ckxew7clguvy3updzfn3t6"
!wget -O LIB.csv "https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv"

--2026-04-13 15:08:00--  https://virginia.box.com/shared/static/959w70gbj2ckxew7clguvy3updzfn3t6
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/959w70gbj2ckxew7clguvy3updzfn3t6 [following]
--2026-04-13 15:08:00--  https://virginia.box.com/public/static/959w70gbj2ckxew7clguvy3updzfn3t6
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/959w70gbj2ckxew7clguvy3updzfn3t6 [following]
--2026-04-13 15:08:01--  https://virginia.app.box.com/public/static/959w70gbj2ckxew7clguvy3updzfn3t6
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!UeMJpstDTbhsd8g2_XdaiRD5rYlOnKPTa-3OrQGuhKOAQPHnHCq2XzgnqJa7YAilxjVayq_xvAXE3s4FSCF40n6Kk_99HDWt5FVIuJYE1_sCbFLBA8IUMY9NZjUvpEZboR_YVyT3hmf7npNmDjTNmTuHlnxtHIK3Oq1HEDTwjaoS7dr9jzG3XCQ4NWS0P6tdOX5Mq6Wi5rdZiQW-TMjRXL8c7exKys3DHqF7qeJ592NlTN-6xWUo_mtHEx9sx0ZiliJDMYFoEOpylEMB3zgFQ-6hWysVo6ULpirt8N9XgzYR6vmoDXZ-rxzPEZLidAfnMuUkjVJ4P2NC0-lvcP9YEBUHlFLAFIPqe_dToK6oH55uJaIePK7WEf-MvEAqfnFsowEi1EhZAX-bjdy7wJNiwt16Q1cEbvz6h5RbG8jGXkmXGP-eLN1QPpdHYGxUqfQBklAAV04l0lkfEBQ0wvgyalRMN01nJD7-PgjpXdR-P_Q9sfsLP_h3Kf9RNN-3Au4TSVtnfnGTYbi3wKnd2YJ7EgHScIZfB4INs1b8uxWPFD9uP3a1ZvBNrl7-Eta4oLnW82_cRBjFdU8SsO6STFyYCc_PDCmym5bspyjk1LTU6VOCEede6Z5vXXYqCgmfeL574V_RpHQRJwjxbYwHOo9UYBk_qq7xE8lrs6p4kt3-YqN1f1xxo5bON6AuWQ0ZJsOlIeS-n8m2elq4E5HjZTB9q1ua-PNkS93KRZBB9hDwN8_IDYfLwmMAkHlfN5sepM_CXmfNt1jN65HUUaQuvLFK75QNuKI70LL9VjU-qEbWI32nJm4EwSx7PEZrau4tettp6vA2j5qmGr6ICJF7P7UaqLLx_MsqH-nk-JWOdmm84zyPYEaAcyScvi_X1NxQ3LQyk3t2KnmlcaXU1Qbv4SX8aUW81eNX3XwGRdLUlrqtSvK28plTNxzqNpQS2DiK331cCv5mDZDOAVh-IDuseLF3brLEpUvX94Zt1hr8g_xEWa-3pV7TMMiwgNVfdYY5jwI4pZEYDu7eA0UY-baOsq0q8rFgGk1D62XPyJBtZoI6R-ln7N8mbzn0RIR5mJ2Bb41uJy3D3Q-vOuOSxTp66XpA2rftybPJM-lnCfHKTQc7magRDPBT1AvoZbaOMoyILO4g6LHc3Bi2LV_R8FSDKS7uIb3YAPcE23Vz8AIRhW1ihBcNWJ54ESmHC4gJj8B5j_KUm_rpwDW5YEf3VypT6c9w5b8JZ0rup98KhXTFsc6x9YejArCBw_BJr1pNFE4ALga0cyuNAlHFBxsMv0VEJVG2-rcF5Om523KlU6gUBsmfUf2SzZPtHvCBL2OZyxrywBFA_RvGRnn___SDnW4F54xmiMxlnTI5vTRr4_AMqxUAx7jxjFqcpxTETELF-i_j8n1cwckM0o-bIcE0cBwWN9Pi46jyZFa7h_1BVSUzd7OJx5YGiaDU1m9FOaoKAPCjePEOpct1HkCDUE1I241vEjLQXakm9LCSKwg./download [following]
--2026-04-13 15:08:01--  https://public.boxcloud.com/d/1/b1!UeMJpstDTbhsd8g2_XdaiRD5rYlOnKPTa-3OrQGuhKOAQPHnHCq2XzgnqJa7YAilxjVayq_xvAXE3s4FSCF40n6Kk_99HDWt5FVIuJYE1_sCbFLBA8IUMY9NZjUvpEZboR_YVyT3hmf7npNmDjTNmTuHlnxtHIK3Oq1HEDTwjaoS7dr9jzG3XCQ4NWS0P6tdOX5Mq6Wi5rdZiQW-TMjRXL8c7exKys3DHqF7qeJ592NlTN-6xWUo_mtHEx9sx0ZiliJDMYFoEOpylEMB3zgFQ-6hWysVo6ULpirt8N9XgzYR6vmoDXZ-rxzPEZLidAfnMuUkjVJ4P2NC0-lvcP9YEBUHlFLAFIPqe_dToK6oH55uJaIePK7WEf-MvEAqfnFsowEi1EhZAX-bjdy7wJNiwt16Q1cEbvz6h5RbG8jGXkmXGP-eLN1QPpdHYGxUqfQBklAAV04l0lkfEBQ0wvgyalRMN01nJD7-PgjpXdR-P_Q9sfsLP_h3Kf9RNN-3Au4TSVtnfnGTYbi3wKnd2YJ7EgHScIZfB4INs1b8uxWPFD9uP3a1ZvBNrl7-Eta4oLnW82_cRBjFdU8SsO6STFyYCc_PDCmym5bspyjk1LTU6VOCEede6Z5vXXYqCgmfeL574V_RpHQRJwjxbYwHOo9UYBk_qq7xE8lrs6p4kt3-YqN1f1xxo5bON6AuWQ0ZJsOlIeS-n8m2elq4E5HjZTB9q1ua-PNkS93KRZBB9hDwN8_IDYfLwmMAkHlfN5sepM_CXmfNt1jN65HUUaQuvLFK75QNuKI70LL9VjU-qEbWI32nJm4EwSx7PEZrau4tettp6vA2j5qmGr6ICJF7P7UaqLLx_MsqH-nk-JWOdmm84zyPYEaAcyScvi_X1NxQ3LQyk3t2KnmlcaXU1Qbv4SX8aUW81eNX3XwGRdLUlrqtSvK28plTNxzqNpQS2DiK331cCv5mDZDOAVh-IDuseLF3brLEpUvX94Zt1hr8g_xEWa-3pV7TMMiwgNVfdYY5jwI4pZEYDu7eA0UY-baOsq0q8rFgGk1D62XPyJBtZoI6R-ln7N8mbzn0RIR5mJ2Bb41uJy3D3Q-vOuOSxTp66XpA2rftybPJM-lnCfHKTQc7magRDPBT1AvoZbaOMoyILO4g6LHc3Bi2LV_R8FSDKS7uIb3YAPcE23Vz8AIRhW1ihBcNWJ54ESmHC4gJj8B5j_KUm_rpwDW5YEf3VypT6c9w5b8JZ0rup98KhXTFsc6x9YejArCBw_BJr1pNFE4ALga0cyuNAlHFBxsMv0VEJVG2-rcF5Om523KlU6gUBsmfUf2SzZPtHvCBL2OZyxrywBFA_RvGRnn___SDnW4F54xmiMxlnTI5vTRr4_AMqxUAx7jxjFqcpxTETELF-i_j8n1cwckM0o-bIcE0cBwWN9Pi46jyZFa7h_1BVSUzd7OJx5YGiaDU1m9FOaoKAPCjePEOpct1HkCDUE1I241vEjLQXakm9LCSKwg./download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.164, 2620:117:bff0:e2::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 79787849 (76M) [text/csv]
Saving to: ‘TFIDF_L2.csv’

TFIDF_L2.csv        100%[===================>]  76.09M  62.7MB/s    in 1.2s

2026-04-13 15:08:03 (62.7 MB/s) - ‘TFIDF_L2.csv’ saved [79787849/79787849]

--2026-04-13 15:08:03--  https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-13 15:08:03--  https://virginia.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-13 15:08:03--  https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!9AOrGvpmn6AFhsU90KO1FHQkuTvaGh3D8Opq759ooekBq_CA81A6ty2qhbXtWbO5k8BBZeB1piD3Iu6Hbv8QXhUvgYP7OCeFcQdQj9nUjkxrB7J-N-6bDXIOenSpyQafsz2mrrdcxJqDSZHwOkVg-E3_eYrmvlonyp0TXR3zuXiMD8xuhdEQAdnbG_8XaOjAuVp9XxdKIkrcR3oC6W5xFtXUE3Bqq-NkegS1S07tPty1XxaCI91l41dVrdOB5SY1cynO3tV0en0uzTHqmEmuhQ4rAJNB31XL0rzubFHuPqiB_2ehDt3nC6_0Z4P55yv0fRqJy9G1WZkd31Zj-xxjh3ted39DVXNCLfNkD8pXNoTnEQPucjJkyv20ki9BmfaxNd_zHGtRVbsb6nF1Ra8h0jWcJUL5VTFkWQnpsGeggR3DyMqyiD9uPG4adUSlRAtg6AwNPHG0kwEBuWjwaTy7UeiQ4iXg01klq5f7am3yE4TQ_XnCerH7vI8s_eEuB--ajpk-e6710aCaq5uvP7Aky13_4fpbns3Y3BPeFonGTKKbEJ3pKXIfOTnLtjoMgRMRWnPXRX1d-tJsTje74BuwiIZpAgXuNejlTE2jie5GTncllLHfTymE2HMO4G5ijPW3S542OVIWObQSMf0LQoLJmpH5DHIsgFQ8xCaCVcaFh7V6g0tbGnO_UO5OZHXUDeCjgmCsbk82YZmLDSzlcodb18UYukFkaqcKtzx6N_0vURznvQh9wYVBveiYv7lI16M1m0vylKr7rdA9e4u299FBrGcKGBp1AirvG3qFLvZVTVvH2qKbMetDrS5TFqE5OhbZgfZgVawaptUarGhD4cwMDajeAUunU2TvBRrfc0xiFJ0vbv7uPYsXC28ZVZnVgRZ-EYcDpDrQ9lCA0xvxnLHr8T7LDXPZrQN_F8BcAy_w6l8P4MvM9Sbk6ZD4WvBR1aZjG4WO-dCJC_QWYfIQULgIP65peOzb8_IcCpq2RjsSP9i76azkExTJuh2vpjkJhSyQ-sVrAUdYqcS4CmJlzTIQOBNxwmYvJB2yntYlcjA_vcRgbLvfKdMBXzQA3p6lyVOJ-yk56Mg93m-k1gsSeiBugSiU04qjU4bGopxNf9OSloeg0S78ImbS3MMrIp5s0gnp6BO2acHcr5pL_lNeuds4fK26huYjQ-frXLJDLY4do2S75ZrjcmNEAfVHyCBd-CXs_AGpSWa3qr7OrE-U8umKoLcOn5fnpYu7yrp-p_6Oj7Gl8Z-tuTONPUhObp2DSXe7-9gOFXqTdL2d8y5KPD6Mg7a1nX7t4qOpZjVWPOVFYfmYrmqGwkKQkun-Ek2KlOBvCMKb5imkVTNk4FlFAnap8I-r59rsH18lV-7WrFrSv7bC65hWIZ70CSRBmcbsUl5ER7gDIwkmxdTH9aG4V7L2NE_DsjkCgh4_QpFgIsGfNLWifRmjIT4ErBwfG3ylIZyP-0MmNm1NIS3PKGayF4JERQ../download [following]
--2026-04-13 15:08:04--  https://public.boxcloud.com/d/1/b1!9AOrGvpmn6AFhsU90KO1FHQkuTvaGh3D8Opq759ooekBq_CA81A6ty2qhbXtWbO5k8BBZeB1piD3Iu6Hbv8QXhUvgYP7OCeFcQdQj9nUjkxrB7J-N-6bDXIOenSpyQafsz2mrrdcxJqDSZHwOkVg-E3_eYrmvlonyp0TXR3zuXiMD8xuhdEQAdnbG_8XaOjAuVp9XxdKIkrcR3oC6W5xFtXUE3Bqq-NkegS1S07tPty1XxaCI91l41dVrdOB5SY1cynO3tV0en0uzTHqmEmuhQ4rAJNB31XL0rzubFHuPqiB_2ehDt3nC6_0Z4P55yv0fRqJy9G1WZkd31Zj-xxjh3ted39DVXNCLfNkD8pXNoTnEQPucjJkyv20ki9BmfaxNd_zHGtRVbsb6nF1Ra8h0jWcJUL5VTFkWQnpsGeggR3DyMqyiD9uPG4adUSlRAtg6AwNPHG0kwEBuWjwaTy7UeiQ4iXg01klq5f7am3yE4TQ_XnCerH7vI8s_eEuB--ajpk-e6710aCaq5uvP7Aky13_4fpbns3Y3BPeFonGTKKbEJ3pKXIfOTnLtjoMgRMRWnPXRX1d-tJsTje74BuwiIZpAgXuNejlTE2jie5GTncllLHfTymE2HMO4G5ijPW3S542OVIWObQSMf0LQoLJmpH5DHIsgFQ8xCaCVcaFh7V6g0tbGnO_UO5OZHXUDeCjgmCsbk82YZmLDSzlcodb18UYukFkaqcKtzx6N_0vURznvQh9wYVBveiYv7lI16M1m0vylKr7rdA9e4u299FBrGcKGBp1AirvG3qFLvZVTVvH2qKbMetDrS5TFqE5OhbZgfZgVawaptUarGhD4cwMDajeAUunU2TvBRrfc0xiFJ0vbv7uPYsXC28ZVZnVgRZ-EYcDpDrQ9lCA0xvxnLHr8T7LDXPZrQN_F8BcAy_w6l8P4MvM9Sbk6ZD4WvBR1aZjG4WO-dCJC_QWYfIQULgIP65peOzb8_IcCpq2RjsSP9i76azkExTJuh2vpjkJhSyQ-sVrAUdYqcS4CmJlzTIQOBNxwmYvJB2yntYlcjA_vcRgbLvfKdMBXzQA3p6lyVOJ-yk56Mg93m-k1gsSeiBugSiU04qjU4bGopxNf9OSloeg0S78ImbS3MMrIp5s0gnp6BO2acHcr5pL_lNeuds4fK26huYjQ-frXLJDLY4do2S75ZrjcmNEAfVHyCBd-CXs_AGpSWa3qr7OrE-U8umKoLcOn5fnpYu7yrp-p_6Oj7Gl8Z-tuTONPUhObp2DSXe7-9gOFXqTdL2d8y5KPD6Mg7a1nX7t4qOpZjVWPOVFYfmYrmqGwkKQkun-Ek2KlOBvCMKb5imkVTNk4FlFAnap8I-r59rsH18lV-7WrFrSv7bC65hWIZ70CSRBmcbsUl5ER7gDIwkmxdTH9aG4V7L2NE_DsjkCgh4_QpFgIsGfNLWifRmjIT4ErBwfG3ylIZyP-0MmNm1NIS3PKGayF4JERQ../download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.164, 2620:117:bff0:e2::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 333596 (326K) [text/csv]
Saving to: ‘LIB.csv’

LIB.csv             100%[===================>] 325.78K  --.-KB/s    in 0.006s

2026-04-13 15:08:04 (52.9 MB/s) - ‘LIB.csv’ saved [333596/333596]

In [4]:
import pandas as pd
TFIDF_L2 = pd.read_csv('TFIDF_L2.csv', delimiter='|', index_col=[0,1,2])
LIB = pd.read_csv('LIB.csv', delimiter='|', index_col=0)

## PCA Components

In [5]:
from sklearn.decomposition import PCA
import numpy as np

pca_engine = PCA(n_components=5)
pca_engine.fit(TFIDF_L2)

COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
COMPS.columns = ["PC{}".format(i) for i in COMPS.columns]
COMPS.index = TFIDF_L2.columns
COMPS.index.name = 'term_str'
COMPS.head()

               PC0       PC1       PC2       PC3       PC4
term_str
a        -0.002289 -0.002043 -0.001101 -0.000119 -0.000969
all      -0.002790 -0.004950 -0.000796  0.002500  0.000028
and      -0.002442 -0.003982 -0.002092  0.001712 -0.002339
around   -0.001855 -0.002173 -0.001955  0.000988 -0.000920
at       -0.001911 -0.003871 -0.002408  0.001567 -0.001959

In [6]:
print("Top 5 positive terms for PC0:")
print(COMPS['PC0'].nlargest(5))

print("\nTop 5 negative terms for PC1:")
print(COMPS['PC1'].nsmallest(5))

Top 5 positive terms for PC0:
term_str
released    0.119626
song        0.075531
lyrics      0.052784
check       0.050403
yet         0.050178
Name: PC0, dtype: float64

Top 5 negative terms for PC1:
term_str
you    -0.010204
love   -0.009202
let    -0.008622
dont   -0.008612
need   -0.008499
Name: PC1, dtype: float64

In [7]:
COMPS.to_csv('/content/DS5001-Final-Project/COMPS.csv', sep='|', index=True)

## PCA DCM

In [8]:
TFIDF_L2.index = (
    TFIDF_L2.index.get_level_values('Artist') + ' — ' +
    TFIDF_L2.index.get_level_values('Title') + ' (' +
    TFIDF_L2.index.get_level_values('Album') + ')'
)
TFIDF_L2.index.name = 'track_id'

In [9]:
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF_L2), index=TFIDF_L2.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM.head()

,PC0,PC1,PC2,PC3,PC4
track_id,,,,,
Ariana Grande — Brand New You (13 (Original Broadway Cast Recording)),-0.032332,0.071247,-0.013300,-0.065710,-0.004599
Ariana Grande — Ariana Grande Tour Guide (Ariana Grande),-0.019869,0.118616,0.003782,-0.092360,0.008104
Ariana Grande — I’m Every Woman/Vogue (Ariana Grande),-0.048779,-0.003187,0.050625,-0.004128,-0.004922
Ariana Grande — Leave Me Lonely (Reprise) (Ariana Grande),-0.024795,0.087238,0.011210,-0.065125,0.032759
Ariana Grande — Love Me Harder/breathin (Ariana Grande),-0.029093,0.081931,0.005862,-0.063612,0.017884

In [10]:
DCM.to_csv('/content/DS5001-Final-Project/DCM.csv', sep='|', index=True)

## PCA Loadings

## PCA Visualization 1

In [11]:
import plotly_express as px
import plotly.io as pio
pio.renderers.default = 'colab'

def vis_pcs(DCM, a, b, label='Artist'):
    LIB_reduced = LIB.loc[DCM.index]
    fig = px.scatter(DCM, f"PC{a}", f"PC{b}",
                    color=LIB_reduced[label],
                    hover_name=LIB_reduced.index,
                    size=LIB_reduced['doc_length_words'],
                    marginal_x='box',
                    height=800,
                    title=f"PCA — PC{a} vs PC{b} colored by {label}")
    fig.update_traces(marker=dict(line=dict(width=0)))
    fig.update_layout(
        xaxis=dict(showgrid=True, gridcolor='lightgrey'),
        yaxis=dict(showgrid=True, gridcolor='lightgrey')
    )
    return fig

def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    fig = px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}",
                      text='term_str',
                      marginal_x='box',
                      height=800,
                      title=f"PCA Loadings — PC{a} vs PC{b}")
    fig.update_traces(marker=dict(line=dict(width=0)))
    fig.update_layout(
        xaxis=dict(showgrid=True, gridcolor='lightgrey'),
        yaxis=dict(showgrid=True, gridcolor='lightgrey')
    )
    return fig

In [21]:
import kaleido
fig1 = vis_pcs(DCM, 0, 1)
pio.write_image(fig1, "/content/DS5001-Final-Project/images/PCA_components_PC0_PC1.png", format="png", scale=2, engine="kaleido")
fig1

In [22]:
fig2 = vis_loadings(COMPS, 0, 1)
pio.write_image(fig2, "/content/DS5001-Final-Project/images/PCA_loadings_PC0_PC1.png", format="png", scale=2, engine="kaleido")
fig2

In [14]:
print("Positive pole (right side):")
print(COMPS['PC0'].nlargest(10))

print("\nNegative pole (left side):")
print(COMPS['PC0'].nsmallest(10))

Positive pole (right side):
term_str
released    0.119626
song        0.075531
lyrics      0.052784
check       0.050403
yet         0.050178
once        0.046168
has         0.040064
please      0.038928
been        0.020751
back        0.018920
Name: PC0, dtype: float64

Negative pole (left side):
term_str
love   -0.004754
oh     -0.004733
yeah   -0.004613
you    -0.004581
baby   -0.004212
want   -0.003929
i      -0.003788
dont   -0.003644
me     -0.003475
we     -0.003448
Name: PC0, dtype: float64

##PCA Visualization 2

In [23]:
fig3 = vis_pcs(DCM, 1, 2)
pio.write_image(fig3, "/content/DS5001-Final-Project/images/PCA_components_PC1_PC2.png", format="png", scale=2, engine="kaleido")
fig3

In [24]:
fig4 = vis_loadings(COMPS, 1, 2)
pio.write_image(fig4, "/content/DS5001-Final-Project/images/PCA_loadings_PC1_PC2.png", format="png", scale=2, engine="kaleido")
fig4

In [17]:
print("Positive pole (right side):")
print(COMPS['PC1'].nlargest(10))

print("\nNegative pole (left side):")
print(COMPS['PC1'].nsmallest(10))

Positive pole (right side):
term_str
la           0.045463
edge         0.005381
christmas    0.004334
chris        0.003527
snippet      0.003429
martin       0.003283
light        0.003094
fa           0.003039
05           0.002851
gaga         0.002839
Name: PC1, dtype: float64

Negative pole (left side):
term_str
you     -0.010204
love    -0.009202
let     -0.008622
dont    -0.008612
need    -0.008499
never   -0.008469
baby    -0.007927
if      -0.007777
ill     -0.007598
back    -0.007238
Name: PC1, dtype: float64

##LDA Topic