<a href="https://colab.research.google.com/github/maggiecrowner/DS5001-Final-Project/blob/main/VOCAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parsed and Annotated Data

In [1]:
! git clone https://github.com/maggiecrowner/DS5001-Final-Project.git

Cloning into 'DS5001-Final-Project'...
remote: Enumerating objects: 263, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 263 (delta 48), reused 4 (delta 4), pack-reused 175 (from 1)
Receiving objects: 100% (263/263), 15.04 MiB | 8.80 MiB/s, done.
Resolving deltas: 100% (99/99), done.

In [2]:
!wget -O CORPUS.csv "https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv"

--2026-04-21 02:07:40--  https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-21 02:07:40--  https://virginia.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-21 02:07:41--  https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!GTmtguS3lPsYHe_JeW7gKez_1U1XzLROzH4-7WTnAIOXTRoBqcgw98uXl3gLIw6o_uC6Kh-hjlW_CC8l1g2woC8af33o9tZHE3S6NYuMup7ZnBfrGkYkY0xClszDDYzRoDvE2jTa2E9kR2JqDWQK4uORoOGd0XfoIpxVb__hV_I7QUU9OYAwM8QDDd2gmH4H1ok-P5D4D06zhiQoF99mkXwd0HyhX8Xlvflk-GiP3HjbY5FKutq7ZTOocA9E0ThE-w1oUVQGx7nom5j7N0ZgUU3uzdvPoPDEP-UpBHb4vxBKGNek8R-DtopKVlBGMRNo9Ws6rtfpej722qHzbJh0gNRQzjAUl5nNKPmrNOA5NMg82HcmRARve5kwXdklDhh5v7wvCLO41Ag8uuDAYYyKCtJWZ99kVp2wen5uS8QTh7O0-rXkJtWAqK302mXaEOGkulX1LeflUSjviKJ5GY993BSgzkpwM9qRgR1LLKp2K3mdyl9FSGtXo6dV18RP3ZYDAPVxYvhW3D1xNqt3v1i-_4n3BhTSScLGHhaMDCFP17GHA5CRtrN49qB5b_DITCpxDZ34_n6-AbXXn3XLfrZMK_j2rJlZxDGM43dZDYh5SSXvxuLtFqe4IEwZ-08G6TMGgfHfqvkS7ZpJvzYQY1Q5VXpKzYYtwpOelqKGV_RaEpzIORH5z-Kaojw0uf114um7zIl51K5vpALpO2I5tX7h6Pk4Qb5Gc9lRxWUvak2kY8pxVkXTibNxJZhnz6Mae4lLB9Nvy0phJc-6IdF32UwRaiQIZoYrrmCM-2IExKGhDA1Rg31NfG6x-7bPbVE5MMqfmnp71E_XULEKCbJyxMgEWXD5BMUxyI0lTg9VPJiH4KDPuVA_MybW1X-zxf0TTINlfKHP5oNJNlBFIJGfhfLqwCBtLMvXg4xbU4czMR3RkPlflhtufLVHe70T3KLPq154rOZ0ucM7PqCjAZzQk7khbeVPGECIzzVIMx9C67SIEf2klh_Fh2YaZWyoNz7MFVqzUOxIhThaTgOudGCuFqlfikeq2NtGH3Kia4YhGwNpPDFaAINz5VNk4BLed3FAEn3AyFlAmflayOxru2gL5EYMkcgdz9FrRkiQqzBb5elhrmD3meH6C0ShmjtK2N8jr9D6pK_V6vC7j2yv-W4530gx_63UtYCiOu9sI9mm9IVCVa_mONX8ZjVSGo1bHeizuaUzU2WyPCa7i2lAhj4rgHsy01Mh7PENoEA7QtvT73LKuF2yk1fEPoaQtvWJjvOxFVF0FupTA2vkvenJd06-gKZtPqERpVGwguRxznkzthNU8juDgM66oZUAt3ZmNk1Ter7Tr8wT3eOadLa-f8yd84Bap-14VEZQM57ZPBXjkyGZo8cgF4mDePX-iQZbwzZZ8FcD1yhBtcHOUIwxO8iPTLASLMOZPZd1CQabThUns2k8lq7aSv6OmnRtKTWJbCss0jcIzDzsTFTLA28CmmFnM8z9QwLY0e0./download [following]
--2026-04-21 02:07:41--  https://public.boxcloud.com/d/1/b1!GTmtguS3lPsYHe_JeW7gKez_1U1XzLROzH4-7WTnAIOXTRoBqcgw98uXl3gLIw6o_uC6Kh-hjlW_CC8l1g2woC8af33o9tZHE3S6NYuMup7ZnBfrGkYkY0xClszDDYzRoDvE2jTa2E9kR2JqDWQK4uORoOGd0XfoIpxVb__hV_I7QUU9OYAwM8QDDd2gmH4H1ok-P5D4D06zhiQoF99mkXwd0HyhX8Xlvflk-GiP3HjbY5FKutq7ZTOocA9E0ThE-w1oUVQGx7nom5j7N0ZgUU3uzdvPoPDEP-UpBHb4vxBKGNek8R-DtopKVlBGMRNo9Ws6rtfpej722qHzbJh0gNRQzjAUl5nNKPmrNOA5NMg82HcmRARve5kwXdklDhh5v7wvCLO41Ag8uuDAYYyKCtJWZ99kVp2wen5uS8QTh7O0-rXkJtWAqK302mXaEOGkulX1LeflUSjviKJ5GY993BSgzkpwM9qRgR1LLKp2K3mdyl9FSGtXo6dV18RP3ZYDAPVxYvhW3D1xNqt3v1i-_4n3BhTSScLGHhaMDCFP17GHA5CRtrN49qB5b_DITCpxDZ34_n6-AbXXn3XLfrZMK_j2rJlZxDGM43dZDYh5SSXvxuLtFqe4IEwZ-08G6TMGgfHfqvkS7ZpJvzYQY1Q5VXpKzYYtwpOelqKGV_RaEpzIORH5z-Kaojw0uf114um7zIl51K5vpALpO2I5tX7h6Pk4Qb5Gc9lRxWUvak2kY8pxVkXTibNxJZhnz6Mae4lLB9Nvy0phJc-6IdF32UwRaiQIZoYrrmCM-2IExKGhDA1Rg31NfG6x-7bPbVE5MMqfmnp71E_XULEKCbJyxMgEWXD5BMUxyI0lTg9VPJiH4KDPuVA_MybW1X-zxf0TTINlfKHP5oNJNlBFIJGfhfLqwCBtLMvXg4xbU4czMR3RkPlflhtufLVHe70T3KLPq154rOZ0ucM7PqCjAZzQk7khbeVPGECIzzVIMx9C67SIEf2klh_Fh2YaZWyoNz7MFVqzUOxIhThaTgOudGCuFqlfikeq2NtGH3Kia4YhGwNpPDFaAINz5VNk4BLed3FAEn3AyFlAmflayOxru2gL5EYMkcgdz9FrRkiQqzBb5elhrmD3meH6C0ShmjtK2N8jr9D6pK_V6vC7j2yv-W4530gx_63UtYCiOu9sI9mm9IVCVa_mONX8ZjVSGo1bHeizuaUzU2WyPCa7i2lAhj4rgHsy01Mh7PENoEA7QtvT73LKuF2yk1fEPoaQtvWJjvOxFVF0FupTA2vkvenJd06-gKZtPqERpVGwguRxznkzthNU8juDgM66oZUAt3ZmNk1Ter7Tr8wT3eOadLa-f8yd84Bap-14VEZQM57ZPBXjkyGZo8cgF4mDePX-iQZbwzZZ8FcD1yhBtcHOUIwxO8iPTLASLMOZPZd1CQabThUns2k8lq7aSv6OmnRtKTWJbCss0jcIzDzsTFTLA28CmmFnM8z9QwLY0e0./download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.165, 2620:117:bff0:69::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 69963573 (67M) [text/csv]
Saving to: ‘CORPUS.csv’

CORPUS.csv          100%[===================>]  66.72M  63.4MB/s    in 1.1s

2026-04-21 02:07:43 (63.4 MB/s) - ‘CORPUS.csv’ saved [69963573/69963573]

In [3]:
import pandas as pd
CORPUS = pd.read_csv('CORPUS.csv', delimiter='|')

## VOCAB

In [4]:
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import numpy as np

ps = PorterStemmer()

n = CORPUS['term_str'].value_counts().rename('n')
doc_term = CORPUS.reset_index().groupby('Title')['term_str'].apply(set)
N_docs = len(doc_term)

df_counts = (CORPUS.reset_index()
             .groupby('term_str')['Title']
             .nunique()
             .rename('df'))

VOCAB = pd.DataFrame({'n': n, 'df': df_counts})
VOCAB.index.name = 'term_str'

VOCAB['p']            = VOCAB['df'] / N_docs
VOCAB['i']            = np.log2(N_docs / VOCAB['df'])
VOCAB['dfidf']        = VOCAB['df'] * VOCAB['i']
VOCAB['porter_stem']  = VOCAB.index.map(lambda t: ps.stem(t))
VOCAB['max_pos']      = CORPUS.groupby('term_str')['pos'].agg(lambda x: x.value_counts().idxmax())
VOCAB['max_pos_group']= CORPUS.groupby('term_str')['pos_group'].agg(lambda x: x.value_counts().idxmax())
VOCAB['stop']         = VOCAB.index.map(lambda t: int(t in ENGLISH_STOP_WORDS))
VOCAB['ngram_length'] = VOCAB.index.map(lambda t: len(t.split()))
VOCAB = VOCAB.drop(columns=['df'])

print(f" VOCAB shape: {VOCAB.shape}")
VOCAB.head()

 VOCAB shape: (19102, 9)

,n,p,i,dfidf,porter_stem,max_pos,max_pos_group,stop,ngram_length
term_str,,,,,,,,,
0,151,0.030345,5.042406,443.731690,0,CD,OTHER,0,1
00,33,0.008621,6.857981,171.449525,00,CD,OTHER,0,1
000,14,0.002069,8.916875,53.501248,000,CD,OTHER,0,1
000s,1,0.000345,11.501837,11.501837,000,CD,OTHER,0,1
004,1,0.000345,11.501837,11.501837,004,CD,OTHER,0,1

In [5]:
VOCAB.to_csv('/content/DS5001-Final-Project/VOCAB.csv', sep='|', index=True)

In [6]:
print("Number of observations/vocab:", len(VOCAB['dfidf']))

Number of observations/vocab: 19102

In [7]:
top20 = (VOCAB[VOCAB['stop'] == 0]
         .sort_values('dfidf', ascending=False)
         .head(20))
print("Top 20 significant words by DFIDF:")
top20[['n', 'p', 'i', 'dfidf', 'porter_stem', 'max_pos_group']]

Top 20 significant words by DFIDF:

             n         p         i        dfidf porter_stem max_pos_group
term_str
say       3023  0.368966  1.438442  1539.133051         say          VERB
baby      5378  0.380000  1.395929  1538.313401        babi          NOUN
time      2992  0.385172  1.376424  1537.465289        time          NOUN
want      4758  0.350000  1.514573  1537.291770        want          VERB
yeah      6556  0.387241  1.368695  1537.044454        yeah          NOUN
pre       2130  0.347586  1.524557  1536.753719         pre          NOUN
youre     4001  0.401724  1.315723  1532.817231        your          NOUN
got       4441  0.404828  1.304620  1531.624457         got          VERB
make      2513  0.324483  1.623786  1527.982882        make          VERB
way       3016  0.314483  1.668947  1522.079820         way          NOUN
let       3175  0.297586  1.748620  1509.059436         let          VERB
ill       2817  0.297241  1.750293  1508.752674         ill          NOUN
wanna     3299  0.292069  1.775619  1503.949315       wanna          VERB
need      3118  0.290345  1.784161  1502.263361        need          VERB
come      2606  0.288621  1.792753  1500.534573        come          VERB
cause     4008  0.455172  1.135515  1498.879761        caus         OTHER
right     2332  0.277586  1.848992  1488.438731       right           ADV
feel      2219  0.272759  1.874303  1482.573911        feel          VERB
oh        7837  0.474138  1.076621  1480.354262          oh         OTHER
think     1789  0.245172  2.028131  1442.001450       think          VERB