<a href="https://colab.research.google.com/github/maggiecrowner/DS5001-Final-Project/blob/main/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Word2Vec

In [4]:
! git clone https://github.com/maggiecrowner/DS5001-Final-Project.git

Cloning into 'DS5001-Final-Project'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 214 (delta 19), reused 4 (delta 4), pack-reused 175 (from 1)
Receiving objects: 100% (214/214), 13.06 MiB | 8.43 MiB/s, done.
Resolving deltas: 100% (70/70), done.

In [5]:
! pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 40.1 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [6]:
import gensim
gensim.__version__
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
from gensim.models import word2vec
from sklearn.manifold import TSNE as tsne

In [7]:
!wget -O CORPUS.csv "https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv"
!wget -O LIB.csv "https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv"

--2026-04-20 13:27:59--  https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-20 13:28:00--  https://virginia.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-20 13:28:00--  https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!QVZKwFi9ocEAG7LA4P8srmijhu6Wkz61arGkJqjJS97c6w60R0MmcnW0hMKE4karZF4mJ6AN4UxHGzfd2GaEZ33IbVP8ZgfV_2YAcNWu0XOaInqfg0d6s_89DSZxQVVZy5rGguWaPHAjnBxhXln3Y8LuRAsL3AMvxa8ZlOe1bq_mT4qU5kJqeykL1BwuR9sBqxm84HiiHBCVZvg2llYSmnLpQwVuCTQYrqhsyWg-TdghxeLGPqfFAdvEoKlRZteexh0f-xcmPqttHXWpbch1dj4Aj3nOtJUC0Ge_0Xvw8Lz493QnRc0xXIBvAETciPCFuGDK-lEDTSUR9G1gieZvfWgCvHf1s6Wz_1ccO6qmUXliYCCDn5f7lZ_jtq1bf4A0p7f5ZruMeeZseKsS3SXAjR-u7a7k9zelNYM8tZMZ_XJK0rg9VNaKa7d4kWYDxmgklTgNAxwTelgi7kd66frYAPd11MQbYFRnI9TRx9IL-cmoFdg_5NXR_N-h9xCtAxcc30fWOk8eNAH63oDh7vjaSSY7OnTHDO-oIY6FXUUuNtHWbipG2EZd5lF0iJwrNv_mhbZsES31znoGBOY-gTJHOrITfVfTizymIJ5eqkFYlRqsok8FElsESoBA3VipVYZ-rcxklxIvFFrhcrzqHXSdBeA0n9lZJt58VS7BGWCJDMfVNZxJHh6ZFoWYvwJmu4eES-zp8mZdXJ9AFQFE0IHu1mGqKXu2FIU9UK6L5eQEUIbnu2IFnfTgjtGEgZIui4aOOMIbXFP1URCVTJd_w3FGQ-2xKeXZSNiIrNR5xm42FklVDhll9VIxwN3x2GD9dwtlfeNuTBiUyVRIOh619bQSCgcLzSqUpjr_AvmPRHF_W6TUKVioifwiQrxeW9vBeH3TobgEI23_jKXRaDgt8acRTeS1NTtiokoNPt2Cdgg1OcSee8oHClar572xAE2Rbq4iB_R_b0zXU90dC-eza3fXcBIFMJ-Wb0RMmGujXMRBOmQ2PRq7lO3JUgRVW6OzZFhaRrCaeOWNNHIuK_0JiCwGvVajLn0YMQjFPB_GJJbhK61JGLLyV5vHaVtm9C-w1ikHOb7djb-naMl7Ond7EKuYbsLdptqTKSTQp8Q95PsU4hs8xYQNVghUW-PbaLnSNexe2GLLy2lY9JfvYdX__YSyLlEepIiAvsBGkrckhLH-tR8qRHRIISHQ9vrEvTi2rGPkQDXwu2DyCxzIm_dyxzbo-cMdm2_P6CVc2LEEKtykYt_ud1Cgwldkg_HiXA7dH1tSsVBbtdkLVErwmQbZ8pQrHawX8DMZTfN3-AGL4Y8Gk6D-LHJOPZRHdOtbJQSIBxij7SblmMMFWQTrQ78EMX3w2NDAC3jcpIhK5zhjjUl8ye5zK_fimiw49rs_f6295Hm-9JsNBUXpOsIkKFWy-fhVLRikU5NMX0pO__2WRvwif2tRSQZJVL9wTEth66AfEu5AByDiI2BabMHWaZlsjsior9Va0JE./download [following]
--2026-04-20 13:28:00--  https://public.boxcloud.com/d/1/b1!QVZKwFi9ocEAG7LA4P8srmijhu6Wkz61arGkJqjJS97c6w60R0MmcnW0hMKE4karZF4mJ6AN4UxHGzfd2GaEZ33IbVP8ZgfV_2YAcNWu0XOaInqfg0d6s_89DSZxQVVZy5rGguWaPHAjnBxhXln3Y8LuRAsL3AMvxa8ZlOe1bq_mT4qU5kJqeykL1BwuR9sBqxm84HiiHBCVZvg2llYSmnLpQwVuCTQYrqhsyWg-TdghxeLGPqfFAdvEoKlRZteexh0f-xcmPqttHXWpbch1dj4Aj3nOtJUC0Ge_0Xvw8Lz493QnRc0xXIBvAETciPCFuGDK-lEDTSUR9G1gieZvfWgCvHf1s6Wz_1ccO6qmUXliYCCDn5f7lZ_jtq1bf4A0p7f5ZruMeeZseKsS3SXAjR-u7a7k9zelNYM8tZMZ_XJK0rg9VNaKa7d4kWYDxmgklTgNAxwTelgi7kd66frYAPd11MQbYFRnI9TRx9IL-cmoFdg_5NXR_N-h9xCtAxcc30fWOk8eNAH63oDh7vjaSSY7OnTHDO-oIY6FXUUuNtHWbipG2EZd5lF0iJwrNv_mhbZsES31znoGBOY-gTJHOrITfVfTizymIJ5eqkFYlRqsok8FElsESoBA3VipVYZ-rcxklxIvFFrhcrzqHXSdBeA0n9lZJt58VS7BGWCJDMfVNZxJHh6ZFoWYvwJmu4eES-zp8mZdXJ9AFQFE0IHu1mGqKXu2FIU9UK6L5eQEUIbnu2IFnfTgjtGEgZIui4aOOMIbXFP1URCVTJd_w3FGQ-2xKeXZSNiIrNR5xm42FklVDhll9VIxwN3x2GD9dwtlfeNuTBiUyVRIOh619bQSCgcLzSqUpjr_AvmPRHF_W6TUKVioifwiQrxeW9vBeH3TobgEI23_jKXRaDgt8acRTeS1NTtiokoNPt2Cdgg1OcSee8oHClar572xAE2Rbq4iB_R_b0zXU90dC-eza3fXcBIFMJ-Wb0RMmGujXMRBOmQ2PRq7lO3JUgRVW6OzZFhaRrCaeOWNNHIuK_0JiCwGvVajLn0YMQjFPB_GJJbhK61JGLLyV5vHaVtm9C-w1ikHOb7djb-naMl7Ond7EKuYbsLdptqTKSTQp8Q95PsU4hs8xYQNVghUW-PbaLnSNexe2GLLy2lY9JfvYdX__YSyLlEepIiAvsBGkrckhLH-tR8qRHRIISHQ9vrEvTi2rGPkQDXwu2DyCxzIm_dyxzbo-cMdm2_P6CVc2LEEKtykYt_ud1Cgwldkg_HiXA7dH1tSsVBbtdkLVErwmQbZ8pQrHawX8DMZTfN3-AGL4Y8Gk6D-LHJOPZRHdOtbJQSIBxij7SblmMMFWQTrQ78EMX3w2NDAC3jcpIhK5zhjjUl8ye5zK_fimiw49rs_f6295Hm-9JsNBUXpOsIkKFWy-fhVLRikU5NMX0pO__2WRvwif2tRSQZJVL9wTEth66AfEu5AByDiI2BabMHWaZlsjsior9Va0JE./download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.164, 2620:117:bff0:e2::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 69963573 (67M) [text/csv]
Saving to: ‘CORPUS.csv’

CORPUS.csv          100%[===================>]  66.72M   145MB/s    in 0.5s

2026-04-20 13:28:01 (145 MB/s) - ‘CORPUS.csv’ saved [69963573/69963573]

--2026-04-20 13:28:01--  https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-20 13:28:01--  https://virginia.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-20 13:28:01--  https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!VWbcpbvxdm9FhzQLq2TY_JpjiTQSJqa1nI_MuTDQvyq5722JCjbJvck3cVElxThAuq9rQEkxQ1PjSgOoesMwVdv0r8wgFGh9_EZGrqbb6nDaXA-oNsZjo_wd4HgDgTK2DpaolS48XiJx2UCeNTgWtJYyeCiQWbqVjcfXOuetIBrdSEcdluoMpi-g9BxzR9Y23zv2hg8xFR7bqZQB3H6CwDfv3FoyxYrb3575GJZNiOO1glzJufkPPNVeZRUpEjq5-IwwbGcLwTpI8ElqgOVWnnjZehvBjDsmDkGg1AHQZL1_NrVcQZ-yKLtKXDQ-iVslcCKvMGsf0Zafotnil_Lt9WabpHnuMwEJ59FKkFwYP-9GwCWw9PB4D80J_15PArQ99QvWnU5ulJRnZILRHDb9-MxNLkWVH_vbwFI7snAnmCmQ3Hkb_7QLLlv6OFUzNfBH8i4Obhjzq8__N3kFnO1wr90mgb1qXBH8V7dT148tjcGhSwoLbAevZN404cLxrdMQ2LbLVwesiYjfYX1jzW-8GX_FiSf7novVo9J9a8BMIl2NklRC1h0sZjz1NGze8tH3bQ0DK0Q032D8J9HgmU8JoawxkMiqaVptFJ7TU2sQs8ybw_duRXc2PKZFjDQT-htfFupkArmepSeBZzOezZStJL3elJrQAzM79it6-3idSjwGU5xE2BcApTkZU_bA5QVtSVqWb96ias2hLh0cydHEHS1nuoAsERjPTyMjexxjBUE2gTNnBmaYOcu5B3Kjv2ElNj-BSy619PkGUg2tZRBBMCAlZt5UITm5ITKycLh_xlWq3elz2y1-x18-5SAel9VHiHvuuRAF7caPzX4EacjRiAZ2k0EGC2xhVxZJXyDsC9o2l_5qgRtY0sHK8PGgSJ7D6FFKfAqf7nUMSgyTDO-geoWOF7yYlq1y9JESvogYdfS1PkjIBofoGU7RZ6kPjeR6UXoy9rpo1C_e7TqV3O4-CBU1wqZn45bca94aHl4M5pljFGKd4di-FWMFXC_BlOacfaxrzgaXdAi2rhIrejjpn4MDz-Ih1kHqKS_YSGvQmtV3HCZdBn72FndVDOpXn1zrd3M2cW2yk_F2ZAr-8bs4ksh0nTEwD4yIHq-sZRafaMKrjTWEJri38YsTHeE-h-KP38eRSG4XS-e4EH3Kv5I42Oe_LmV2T76m5eaFQPJCFwVmqYqZ4jCkzv1CwezE-PdZPxwmQQ3CarcUbGjoGN-jPfhHHlTzjC2jJeT9n9C8048KP4RDiBc1CgynkaJGqAQc-20DerTWOBvWdS7tto_mlgTe4vQAIQaAZ910-nboSDn4P_NOR9_-BXGYv6XZM2fpsFB4JUcqLLmCvCfQSgXhjzF0P3NoRPkGHHosabCJYsVawCPYOaH089-EwXK2aeTC2ZcCXLnVsrUvzxBuk1o1Q2UXNdJBYuNwTPXxukGWDKoi83p5NMl0DQAr_hGYCFDufJlBNdkzfNriPzswMTXt/download [following]
--2026-04-20 13:28:02--  https://public.boxcloud.com/d/1/b1!VWbcpbvxdm9FhzQLq2TY_JpjiTQSJqa1nI_MuTDQvyq5722JCjbJvck3cVElxThAuq9rQEkxQ1PjSgOoesMwVdv0r8wgFGh9_EZGrqbb6nDaXA-oNsZjo_wd4HgDgTK2DpaolS48XiJx2UCeNTgWtJYyeCiQWbqVjcfXOuetIBrdSEcdluoMpi-g9BxzR9Y23zv2hg8xFR7bqZQB3H6CwDfv3FoyxYrb3575GJZNiOO1glzJufkPPNVeZRUpEjq5-IwwbGcLwTpI8ElqgOVWnnjZehvBjDsmDkGg1AHQZL1_NrVcQZ-yKLtKXDQ-iVslcCKvMGsf0Zafotnil_Lt9WabpHnuMwEJ59FKkFwYP-9GwCWw9PB4D80J_15PArQ99QvWnU5ulJRnZILRHDb9-MxNLkWVH_vbwFI7snAnmCmQ3Hkb_7QLLlv6OFUzNfBH8i4Obhjzq8__N3kFnO1wr90mgb1qXBH8V7dT148tjcGhSwoLbAevZN404cLxrdMQ2LbLVwesiYjfYX1jzW-8GX_FiSf7novVo9J9a8BMIl2NklRC1h0sZjz1NGze8tH3bQ0DK0Q032D8J9HgmU8JoawxkMiqaVptFJ7TU2sQs8ybw_duRXc2PKZFjDQT-htfFupkArmepSeBZzOezZStJL3elJrQAzM79it6-3idSjwGU5xE2BcApTkZU_bA5QVtSVqWb96ias2hLh0cydHEHS1nuoAsERjPTyMjexxjBUE2gTNnBmaYOcu5B3Kjv2ElNj-BSy619PkGUg2tZRBBMCAlZt5UITm5ITKycLh_xlWq3elz2y1-x18-5SAel9VHiHvuuRAF7caPzX4EacjRiAZ2k0EGC2xhVxZJXyDsC9o2l_5qgRtY0sHK8PGgSJ7D6FFKfAqf7nUMSgyTDO-geoWOF7yYlq1y9JESvogYdfS1PkjIBofoGU7RZ6kPjeR6UXoy9rpo1C_e7TqV3O4-CBU1wqZn45bca94aHl4M5pljFGKd4di-FWMFXC_BlOacfaxrzgaXdAi2rhIrejjpn4MDz-Ih1kHqKS_YSGvQmtV3HCZdBn72FndVDOpXn1zrd3M2cW2yk_F2ZAr-8bs4ksh0nTEwD4yIHq-sZRafaMKrjTWEJri38YsTHeE-h-KP38eRSG4XS-e4EH3Kv5I42Oe_LmV2T76m5eaFQPJCFwVmqYqZ4jCkzv1CwezE-PdZPxwmQQ3CarcUbGjoGN-jPfhHHlTzjC2jJeT9n9C8048KP4RDiBc1CgynkaJGqAQc-20DerTWOBvWdS7tto_mlgTe4vQAIQaAZ910-nboSDn4P_NOR9_-BXGYv6XZM2fpsFB4JUcqLLmCvCfQSgXhjzF0P3NoRPkGHHosabCJYsVawCPYOaH089-EwXK2aeTC2ZcCXLnVsrUvzxBuk1o1Q2UXNdJBYuNwTPXxukGWDKoi83p5NMl0DQAr_hGYCFDufJlBNdkzfNriPzswMTXt/download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.164, 2620:117:bff0:e2::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 324648 (317K) [text/csv]
Saving to: ‘LIB.csv’

LIB.csv             100%[===================>] 317.04K  --.-KB/s    in 0.01s

2026-04-20 13:28:02 (31.2 MB/s) - ‘LIB.csv’ saved [324648/324648]

In [8]:
CORPUS = pd.read_csv('CORPUS.csv', delimiter='|', index_col=[0,1,2,3])
LIB = pd.read_csv('LIB.csv', delimiter='|', index_col=0)

##VOCAB_W2V

In [9]:
BAG = ['Artist', 'Album', 'Title']
docs = CORPUS.groupby(BAG).term_str.apply(list).tolist()

In [10]:
for i in range(5):
    print(f"Doc {i}:", docs[i])

Doc 0: ['cassie', 'i', 'saw', 'the', 'cover', 'and', 'judged', 'the', 'book', 'i', 'turned', 'away', 'without', 'a', 'second', 'look', 'but', 'now', 'now', 'now', 'i', 'see', 'a', 'brand', 'new', 'you', 'i', 'told', 'myself', 'i', 'better', 'run', 'and', 'hide', 'i', 'never', 'noticed', 'what', 'was', 'there', 'inside', 'but', 'now', 'now', 'now', 'i', 'see', 'a', 'brand', 'new', 'you', 'and', 'i', 'cant', 'stop', 'myself', 'from', 'lovin', 'evry', 'itty', 'bitty', 'thang', 'you', 'do', 'all', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'charlotte', 'i', 'didnt', 'know', 'where', 'i', 'was', 'meant', 'to', 'be', 'i', 'figured', 'no', 'one', 'would', 'be', 'there', 'for', 'me', 'but', 'now', 'now', 'now', 'i', 'see', 'a', 'brand', 'new', 'you', 'girls', 'oohoo', 'all', 'now', 'now', 'now', 'you', 'you', 'i', 'see', 'a', 'brand', 'new', 'you', 'molly', 'charlotte', 'i', 'never', 'knew', 'that', 'you', 'could', 'understand', 'molly', 'charlotte', 'cassie', 'but', 'i', 'looked', 'up', 'and', 'you', 'reached', 'out', 'your', 'hand', 'and', 'now', 'now', 'now', 'i', 'see', 'a', 'brand', 'new', 'you', 'charlotte', 'i', 'opened', 'my', 'eyes', 'and', 'theres', 'a', 'great', 'big', 'world', 'around', 'i', 'opened', 'my', 'eyes', 'and', 'just', 'look', 'just', 'look', 'look', 'at', 'what', 'i', 'found', 'all', 'now', 'now', 'now', 'i', 'opened', 'my', 'eyes', 'ooh', 'i', 'opened', 'my', 'eyes', 'girls', 'nanana', 'nanana', 'nananana', 'nanana', 'nanana', 'nananana', 'nanana', 'nanana', 'nananana', 'nanana', 'nanana', 'nananana', 'all', 'nanana', 'nanana', 'nananana', 'nanana', 'nanana', 'nananana', 'hey', 'yeah', 'charlotte', 'cassie', 'i', 'opened', 'my', 'eyes', 'and', 'theres', 'a', 'great', 'big', 'world', 'around', 'i', 'opened', 'my', 'eyes', 'all', 'i', 'opened', 'my', 'eyes', 'ooh', 'i', 'opened', 'my', 'eyes', 'cassie', 'and', 'just', 'look', 'just', 'look', 'look', 'at', 'what', 'i', 'found', 'all', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you', 'hoo', 'i', 'see', 'a', 'brand', 'new', 'you']
Doc 1: ['the', 'honeymoon', 'tour', '05', 'the', 'honeymoon', 'tour', 'setlist', 'the', 'honeymoon', 'tour', 'costumes', 'the', 'honeymoon', 'tour', 'special', 'guests', 'im', 'every', 'womanvogue', 'dangerous', 'woman', 'tour', '07', 'dangerous', 'woman', 'tour', 'setlist', 'leave', 'me', 'lonely', 'reprise', 'sweetener', 'world', 'tour', '09', 'sweetener', 'world', 'tour', 'dates', 'sweetener', 'world', 'tour', 'setlist', 'sweetener', 'world', 'tour', 'costumes', 'sweetener', 'world', 'tour', 'special', 'guests', 'love', 'me', 'harderbreathin', 'right', 'thereyoull', 'never', 'knowbreak', 'your', 'heart', 'right', 'back']
Doc 2: ['iew', 'whatever', 'you', 'want', 'whatever', 'you', 'need', 'anything', 'you', 'want', 'done', 'baby', 'ill', 'do', 'it', 'naturally', 'cause', 'im', 'every', 'woman', 'every', 'woman', 'its', 'all', 'in', 'me', 'its', 'all', 'in', 'me', 'vogue', 'ladies', 'with', 'an', 'attitude', 'fellows', 'that', 'were', 'in', 'the', 'mood', 'dont', 'just', 'stand', 'there', 'lets', 'get', 'to', 'it', 'strike', 'a', 'pose', 'theres', 'nothing', 'to', 'it', 'greta', 'garbo', 'and', 'monroe', 'dietrich', 'and', 'dimaggio', 'marlon', 'brando', 'jimmy', 'dean', 'on', 'the', 'cover', 'of', 'a', 'magazine', 'grace', 'kelly', 'harlow', 'jean', 'picture', 'of', 'a', 'beauty', 'queen', 'gene', 'kelly', 'fred', 'astaire', 'ginger', 'rogers', 'dance', 'on', 'air', 'they', 'had', 'style', 'they', 'had', 'grace', 'rita', 'hayworth', 'gave', 'good', 'face', 'lauren', 'katherine', 'lana', 'too', 'bette', 'davis', 'we', 'love', 'you', 'ladies', 'with', 'an', 'attitude', 'fellows', 'that', 'were', 'in', 'the', 'mood', 'dont', 'just', 'stand', 'there', 'lets', 'get', 'to', 'it', 'strike', 'a', 'pose', 'theres', 'nothing', 'to', 'it', 'iew', 'im', 'every', 'woman', 'its', 'all', 'in', 'me', 'anything', 'you', 'want', 'done', 'baby', 'i', 'do', 'it', 'naturally', 'im', 'every', 'woman', 'its', 'all', 'in', 'me', 'i', 'can', 'read', 'your', 'thoughts', 'right', 'now', 'every', 'one', 'from', 'a', 'to', 'z', 'whoa', 'oh', 'whoa', 'oh', 'whoa', 'iew', 'i', 'can', 'cast', 'a', 'spell', 'see', 'but', 'you', 'cant', 'tell', 'mix', 'a', 'special', 'groove', 'put', 'fire', 'inside', 'of', 'you', 'anytime', 'you', 'feel', 'danger', 'or', 'fear', 'then', 'instantly', 'i', 'will', 'appear', 'yeah', 'oh', 'iew', 'im', 'every', 'woman', 'its', 'all', 'in', 'me', 'anything', 'you', 'want', 'done', 'baby', 'i', 'do', 'it', 'naturally', 'whoa', 'whoa', 'whoa', 'whoa', 'whoa', 'whoa', 'iew', 'i', 'can', 'sense', 'your', 'needs', 'like', 'rain', 'onto', 'the', 'seeds', 'i', 'can', 'make', 'a', 'rhyme', 'of', 'confusion', 'in', 'your', 'mind', 'and', 'when', 'it', 'comes', 'down', 'to', 'some', 'good', 'old', 'fashioned', 'love', 'i', 'got', 'it', 'i', 'got', 'it', 'i', 'got', 'it', 'got', 'it', 'baby', 'baby', 'iew', 'im', 'every', 'woman', 'its', 'all', 'in', 'me', 'anything', 'you', 'want', 'done', 'baby', 'i', 'do', 'it', 'naturally', 'im', 'every', 'woman', 'its', 'all', 'in', 'me', 'i', 'can', 'read', 'your', 'thoughts', 'right', 'now', 'every', 'one', 'from', 'a', 'to', 'z', 'whoa', 'oh', 'whoa', 'oh', 'whoa', '4', 'vogue', 'look', 'around', 'everywhere', 'you', 'turn', 'is', 'heartache', 'its', 'everywhere', 'that', 'you', 'go', 'look', 'around', 'you', 'try', 'everything', 'you', 'can', 'to', 'escape', 'the', 'pain', 'of', 'life', 'that', 'you', 'know', 'life', 'that', 'you', 'know', 'when', 'all', 'else', 'fails', 'and', 'you', 'long', 'to', 'be', 'something', 'better', 'than', 'you', 'are', 'today', 'i', 'know', 'a', 'place', 'where', 'you', 'can', 'get', 'away', 'its', 'called', 'a', 'dance', 'floor', 'and', 'heres', 'what', 'its', 'for', 'so', 'vogue', 'come', 'on', 'vogue', 'let', 'your', 'body', 'move', 'to', 'the', 'music', 'move', 'to', 'the', 'music', 'hey', 'hey', 'hey', 'come', 'on', 'vogue', 'let', 'your', 'body', 'go', 'with', 'the', 'flow', 'go', 'with', 'the', 'flow', 'you', 'know', 'you', 'can', 'do', 'it', 'iew', 'i', 'aint', 'bragging', 'because', 'im', 'the', 'one', 'just', 'ask', 'me', 'oh', 'it', 'shall', 'be', 'done', 'and', 'dont', 'bother', 'to', 'compare', 'vocalizing', 'vogue', 'im', 'every', 'woman', 'im', 'every', 'woman', 'strike', 'a', 'pose', 'theres', 'nothing', 'to', 'it', 'dont', 'just', 'stand', 'there', 'lets', 'get', 'to', 'it', 'strike', 'a', 'pose', 'theres', 'nothing', 'to', 'it', 'strike', 'a', 'pose', 'theres', 'nothing', 'to', 'it', 'vogue']
Doc 3: ['theres', 'a', 'dangerous', 'love', 'boy', 'youre', 'no', 'good', 'for', 'me', 'darling', 'yeah', 'you', 'turn', 'me', 'away', 'like', 'im', 'begging', 'for', 'a', 'dollar', 'danger', 'baby', 'oh', 'how', 'you', 'hold', 'me', 'i', 'get', 'a', 'chill', 'inside', 'and', 'nothing', 'frightens', 'me', 'darlin', 'danger', 'danger', 'dangerous', 'darlin', 'danger', 'danger', 'dangerous', 'boy', 'danger', 'danger', 'dangerous', 'darlin', 'hes', 'a', 'dangerous', 'boy', 'nanananana', 'nanananana', 'baby', 'nanananana', 'nananananananana', 'nanananana', 'baby', 'nanananana', 'baby', 'nanananana', 'nanana', 'hes', 'a', 'dangerous', 'boy']
Doc 4: ['lmh', 'tell', 'me', 'something', 'i', 'need', 'to', 'know', 'then', 'take', 'my', 'breath', 'and', 'never', 'let', 'it', 'go', 'if', 'you', 'just', 'let', 'me', 'invade', 'your', 'space', 'ill', 'take', 'the', 'pleasure', 'take', 'it', 'with', 'the', 'pain', 'and', 'if', 'in', 'the', 'moment', 'i', 'bite', 'my', 'lip', 'baby', 'in', 'that', 'moment', 'youll', 'know', 'this', 'is', 'something', 'bigger', 'than', 'us', 'and', 'beyond', 'bliss', 'give', 'me', 'a', 'reason', 'to', 'believe', 'it', 'lmh', 'cause', 'if', 'you', 'want', 'to', 'keep', 'me', 'you', 'gotta', 'gotta', 'gotta', 'gotta', 'got', 'to', 'love', 'me', 'harder', 'and', 'if', 'you', 'really', 'need', 'me', 'you', 'gotta', 'gotta', 'gotta', 'gotta', 'got', 'to', 'love', 'me', 'harder', 'lolove', 'me', 'harder', 'oohoohoohooh', 'love', 'me', 'love', 'me', 'love', 'me', 'oohoohoohooh', 'breathin', 'cigam', 'gnihtemos', 'od', 'ot', 'thgin', 'laiceps', 'ruoy', 'sthginot', 'tub', 'breathin', 'some', 'days', 'things', 'just', 'take', 'way', 'too', 'much', 'of', 'my', 'energy', 'i', 'look', 'up', 'and', 'the', 'whole', 'rooms', 'spinning', 'you', 'take', 'my', 'cares', 'away', 'i', 'can', 'so', 'overcomplicate', 'people', 'tell', 'me', 'to', 'medicate', 'pre', 'breathin', 'feel', 'my', 'blood', 'runnin', 'swear', 'the', 'skys', 'fallin', 'i', 'know', 'that', 'all', 'this', 'shits', 'fabricated', 'time', 'goes', 'by', 'and', 'i', 'cant', 'control', 'my', 'mind', 'dont', 'know', 'what', 'else', 'to', 'try', 'but', 'you', 'tell', 'me', 'every', 'time', 'breathin', 'just', 'keep', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'oh', 'i', 'gotta', 'keep', 'keep', 'on', 'breathin', 'just', 'keep', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'oh', 'i', 'gotta', 'keep', 'keep', 'on', 'breathin', 'breathin', 'sometimes', 'its', 'hard', 'to', 'find', 'find', 'my', 'way', 'up', 'into', 'the', 'clouds', 'tune', 'it', 'out', 'they', 'can', 'be', 'so', 'loud', 'you', 'remind', 'me', 'of', 'a', 'time', 'when', 'things', 'werent', 'so', 'complicated', 'all', 'i', 'need', 'is', 'to', 'see', 'your', 'face', 'pre', 'breathin', 'feel', 'my', 'blood', 'runnin', 'swear', 'the', 'skys', 'fallin', 'i', 'know', 'that', 'all', 'this', 'shits', 'fabricated', 'time', 'goes', 'by', 'and', 'i', 'cant', 'control', 'my', 'mind', 'dont', 'know', 'what', 'else', 'to', 'try', 'but', 'you', 'tell', 'me', 'every', 'time', 'breathin', 'just', 'keep', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'oh', 'i', 'gotta', 'keep', 'i', 'keep', 'on', 'breathin', 'just', 'keep', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'oh', 'i', 'gotta', 'keep', 'i', 'keep', 'on', 'breathin', 'mmm', 'yeah', 'breathin', 'my', 'my', 'air', 'my', 'my', 'air', 'my', 'my', 'air', 'my', 'air', 'my', 'my', 'air', 'my', 'my', 'air', 'my', 'my', 'air', 'yeah', 'breathin', 'just', 'keep', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'oh', 'i', 'gotta', 'keep', 'i', 'keep', 'on', 'breathin', 'just', 'keep', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'breathin', 'and', 'oh', 'i', 'gotta', 'keep', 'i', 'keep', 'on', 'breathin', 'mmm', 'yeah', 'breathin', 'feel', 'my', 'blood', 'runnin', 'swear', 'the', 'skys', 'fallin', 'i', 'keep', 'on', 'breathin', 'oh', 'yeah', 'time', 'goes', 'by', 'and', 'i', 'cant', 'control', 'my', 'mind', 'i', 'keep', 'on', 'breathin', 'mmm', 'yeah']

In [11]:
w2v_params = dict(
    window = 2,
    vector_size = 256,
    min_count = 50,
    workers = 1,
    seed = 42
)

In [12]:
model = word2vec.Word2Vec(docs, **w2v_params)

In [13]:
VOCAB_W2V = pd.DataFrame(model.wv.vectors, index=model.wv.index_to_key)
VOCAB_W2V.index.name = 'term_str'
VOCAB_W2V.head()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
term_str,,,,,,,,,,,,,,,,,,,,,
you,-0.308494,0.309915,0.250957,-0.057719,-0.176610,0.191089,-0.162562,0.111748,-0.094716,-0.535048,...,0.359891,0.025945,0.524044,-0.390012,0.191067,-0.198841,-0.414415,-0.016796,0.018161,-0.297565
i,0.009788,0.027571,0.063070,0.263756,-0.037988,-0.208809,-0.243729,0.477627,-0.307536,-0.289842,...,0.392268,-0.080085,0.263089,-0.548695,0.251925,-0.106512,-0.433913,-0.085959,0.390771,-0.155213
the,0.140901,0.328074,0.302502,-0.720678,0.437081,-0.001589,-0.031509,0.021101,-0.376232,-0.253951,...,-0.185364,-0.449622,-0.189926,0.100873,0.703116,0.230248,-0.217139,-0.150823,0.210721,0.345244
me,-0.480064,0.308382,0.382300,0.059012,-0.771272,0.259622,0.047364,0.044105,-0.152536,-0.411286,...,0.224636,0.475741,-0.066157,-0.784378,-0.139575,-0.293420,-0.373292,-0.183246,-0.016805,0.144870
and,-0.138743,-0.153742,-0.160919,0.086450,-0.273146,-0.243020,-0.016555,-0.235279,-0.138533,0.014349,...,0.241470,-0.139255,0.351895,0.141441,0.025976,-0.108093,0.019672,0.023643,-0.326293,-0.326013

In [14]:
VOCAB_W2V.to_csv("/content/DS5001-Final-Project/VOCAB_W2V.csv", sep="|", index=True)

## Word2vec tSNE Plot

In [15]:
tsne_params = dict(
    perplexity=40,
    n_components=2,
    init='pca',
    max_iter=2500,
    random_state=43
)

tsne_engine = tsne(**tsne_params)

TSNE = pd.DataFrame(
    tsne_engine.fit_transform(VOCAB_W2V),
    columns=['x','y'],
    index=VOCAB_W2V.index)

TSNE.head()

                  x          y
term_str
you        0.707692   2.775519
i          0.935388   3.123217
the      -10.254567 -12.246292
me         6.849462   6.727933
and        1.777331   4.121892

In [19]:
! pip install kaleido==0.2.1

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'plotly'

In [21]:
import plotly.io as pio
pio.renderers.default = 'colab'
import kaleido

fig = px.scatter(TSNE.reset_index(), 'x', 'y',
        text='term_str',
        hover_name='term_str',
        height=1000,
        title='tSNE Plot',
        width=1200)\
    .update_traces(
        mode='markers+text',
        textfont=dict(color='black', size=14, family='Arial'),
        textposition='top center')

import time
time.sleep(2)
pio.write_image(fig, "/content/DS5001-Final-Project/images/tSNE_plot.png", format="png", scale=2, engine="kaleido")
fig